site_name: QuickServer Documents
theme: readthedocs

markdown_extensions: [extra, codehilite, headerid]
use_directory_urls: false

pages:
- [index.md, Home]
- [about.md, About]
- [changelog.md, Changelog]
